# Generated by Django 5.0.4 on 2024-04-25 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='student',
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
